import { PublicKey } from "@solana/web3.js";
export declare const MAINNET_ENDPOINT = "https://api.mainnet-beta.solana.com";
export declare const DEVNET_ENDPOINT = "https://api.devnet.solana.com";
export declare const LOCALNET_ENDPOINT = "http://localhost:8899";
export declare const MAINNET_GOVERNANCE_ADDRESS: PublicKey;
export declare const DEVNET_GOVERNANCE_ADDRESS: PublicKey;
export declare const LOCALNET_GOVERNANCE_ADDRESS: PublicKey;
export declare const MAINNET_STAKING_ADDRESS: PublicKey;
export declare const LOCALNET_STAKING_ADDRESS: PublicKey;
export declare const DEVNET_STAKING_ADDRESS: PublicKey;
export declare const MAINNET_REALM_ID: PublicKey;
export declare const LOCALNET_REALM_ID: PublicKey;
export declare const DEVNET_REALM_ID: PublicKey;
export declare const MAINNET_PYTH_MINT: PublicKey;
export declare const DEVNET_PYTH_MINT: PublicKey;
