"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DEVNET_PYTH_MINT = exports.MAINNET_PYTH_MINT = exports.DEVNET_REALM_ID = exports.LOCALNET_REALM_ID = exports.MAINNET_REALM_ID = exports.DEVNET_STAKING_ADDRESS = exports.LOCALNET_STAKING_ADDRESS = exports.MAINNET_STAKING_ADDRESS = exports.LOCALNET_GOVERNANCE_ADDRESS = exports.DEVNET_GOVERNANCE_ADDRESS = exports.MAINNET_GOVERNANCE_ADDRESS = exports.LOCALNET_ENDPOINT = exports.DEVNET_ENDPOINT = exports.MAINNET_ENDPOINT = void 0;
const web3_js_1 = require("@solana/web3.js");
exports.MAINNET_ENDPOINT = "https://api.mainnet-beta.solana.com";
exports.DEVNET_ENDPOINT = "https://api.devnet.solana.com";
exports.LOCALNET_ENDPOINT = "http://localhost:8899";
exports.MAINNET_GOVERNANCE_ADDRESS = new web3_js_1.PublicKey("GovFUVGZWWwyoLq8rhnoVWknRFkhDSbQiSoREJ5LiZCV");
exports.DEVNET_GOVERNANCE_ADDRESS = new web3_js_1.PublicKey("GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw");
exports.LOCALNET_GOVERNANCE_ADDRESS = new web3_js_1.PublicKey("GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw");
exports.MAINNET_STAKING_ADDRESS = new web3_js_1.PublicKey("sta99txADjRfwHQQMNckb8vUN4jcAAhN2HBMTR2Ah6d");
exports.LOCALNET_STAKING_ADDRESS = new web3_js_1.PublicKey("Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS");
exports.DEVNET_STAKING_ADDRESS = new web3_js_1.PublicKey("sta99txADjRfwHQQMNckb8vUN4jcAAhN2HBMTR2Ah6d");
exports.MAINNET_REALM_ID = new web3_js_1.PublicKey("A1f6LNEymJSSJsEVCL1FSgtS1jA9dNTC4ni8SkmbwQjG");
exports.LOCALNET_REALM_ID = new web3_js_1.PublicKey("44xGQELUXXD1TiLEMc73RBnCxeW8XKw27LyJNpt2G8bF");
exports.DEVNET_REALM_ID = exports.LOCALNET_REALM_ID;
exports.MAINNET_PYTH_MINT = new web3_js_1.PublicKey("3ho8ZM4JVqJzD56FADKdW7NTG5Tv6GiBPFUvyRXMy35Q");
exports.DEVNET_PYTH_MINT = new web3_js_1.PublicKey("7Bd6bEH4wHTMmov8D2WTXgxzLJcxJYczqE5NaDtZdhF6");
