/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_wasmpositiondata_free(a: number): void;
export function __wbg_lockedbalancesummary_free(a: number): void;
export function __wbg_get_lockedbalancesummary_locking(a: number, b: number): void;
export function __wbg_set_lockedbalancesummary_locking(a: number, b: number, c: number): void;
export function __wbg_get_lockedbalancesummary_locked(a: number, b: number): void;
export function __wbg_set_lockedbalancesummary_locked(a: number, b: number, c: number): void;
export function __wbg_get_lockedbalancesummary_unlocking(a: number, b: number): void;
export function __wbg_set_lockedbalancesummary_unlocking(a: number, b: number, c: number): void;
export function __wbg_get_lockedbalancesummary_preunlocking(a: number, b: number): void;
export function __wbg_set_lockedbalancesummary_preunlocking(a: number, b: number, c: number): void;
export function wasmpositiondata_from_buffer(a: number, b: number, c: number): void;
export function wasmpositiondata_getPositionState(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function wasmpositiondata_isPositionVoting(a: number, b: number, c: number): void;
export function wasmpositiondata_getLockedBalanceSummary(a: number, b: number, c: number, d: number, e: number): void;
export function wasmpositiondata_getWithdrawable(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): void;
export function wasmpositiondata_getVoterWeight(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function __wbg_wasmtargetmetadata_free(a: number): void;
export function wasmtargetmetadata_from_buffer(a: number, b: number, c: number): void;
export function wasmtargetmetadata_getCurrentAmountLocked(a: number, b: number, c: number, d: number): void;
export function getNextVesting(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): void;
export function getUnvestedBalance(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): void;
export function getUnixTime(a: number, b: number, c: number): void;
export function constants_MAX_VOTER_WEIGHT(a: number): void;
export function constants_GOVERNANCE_PROGRAM(): number;
export function constants_AUTHORITY_SEED(): number;
export function constants_CUSTODY_SEED(): number;
export function constants_STAKE_ACCOUNT_METADATA_SEED(): number;
export function constants_CONFIG_SEED(): number;
export function constants_VOTER_RECORD_SEED(): number;
export function constants_TARGET_SEED(): number;
export function constants_MAX_VOTER_RECORD_SEED(): number;
export function constants_VOTING_TARGET_SEED(): number;
export function constants_DATA_TARGET_SEED(): number;
export function __wbg_constants_free(a: number): void;
export function constants_MAX_POSITIONS(): number;
export function constants_POSITIONS_ACCOUNT_SIZE(): number;
export function constants_POSITION_BUFFER_SIZE(): number;
export function __wbg_vestingevent_free(a: number): void;
export function __wbg_get_vestingevent_time(a: number, b: number): void;
export function __wbg_set_vestingevent_time(a: number, b: number, c: number): void;
export function __wbg_get_vestingevent_amount(a: number, b: number): void;
export function __wbg_set_vestingevent_amount(a: number, b: number, c: number): void;
export function systeminstruction_createAccount(a: number, b: number, c: number, d: number, e: number, f: number, g: number): number;
export function systeminstruction_createAccountWithSeed(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number): number;
export function systeminstruction_assign(a: number, b: number): number;
export function systeminstruction_assignWithSeed(a: number, b: number, c: number, d: number, e: number): number;
export function systeminstruction_transfer(a: number, b: number, c: number, d: number): number;
export function systeminstruction_transferWithSeed(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): number;
export function systeminstruction_allocate(a: number, b: number, c: number): number;
export function systeminstruction_allocateWithSeed(a: number, b: number, c: number, d: number, e: number, f: number, g: number): number;
export function systeminstruction_createNonceAccount(a: number, b: number, c: number, d: number, e: number): number;
export function systeminstruction_advanceNonceAccount(a: number, b: number): number;
export function systeminstruction_withdrawNonceAccount(a: number, b: number, c: number, d: number, e: number): number;
export function systeminstruction_authorizeNonceAccount(a: number, b: number, c: number): number;
export function init(): void;
export function __wbg_message_free(a: number): void;
export function __wbg_get_message_recent_blockhash(a: number): number;
export function __wbg_set_message_recent_blockhash(a: number, b: number): void;
export function hash_constructor(a: number, b: number): void;
export function hash_toString(a: number, b: number): void;
export function hash_equals(a: number, b: number): number;
export function hash_toBytes(a: number, b: number): void;
export function __wbg_hash_free(a: number): void;
export function __wbg_instruction_free(a: number): void;
export function __wbg_instructions_free(a: number): void;
export function instructions_constructor(): number;
export function instructions_push(a: number, b: number): void;
export function __wbg_pubkey_free(a: number): void;
export function pubkey_constructor(a: number, b: number): void;
export function pubkey_toString(a: number, b: number): void;
export function pubkey_isOnCurve(a: number): number;
export function pubkey_equals(a: number, b: number): number;
export function pubkey_toBytes(a: number, b: number): void;
export function pubkey_createWithSeed(a: number, b: number, c: number, d: number, e: number): void;
export function pubkey_createProgramAddress(a: number, b: number, c: number, d: number): void;
export function pubkey_findProgramAddress(a: number, b: number, c: number, d: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
