[package]
name = "profile"
version = "1.0.0"
description = "Created with Anchor"
edition = "2018"

[features]
mock-clock = []
idl-build = ["anchor-lang/idl-build"]

[lib]
crate-type = ["cdylib", "lib"]
name = "profile"

[dependencies]
anchor-lang = {workspace = true, features = ["init-if-needed"]}
