[package]
name = "profile"
version = "1.0.0"
description = "Created with Anchor"
edition = "2018"

[features]
mock-clock = []

[lib]
crate-type = ["cdylib", "lib"]
name = "profile"

[dependencies]
anchor-lang = {version ="0.24.2", features = ["init-if-needed"]}
