# This workflow will run `anchor test`
name: Api CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.13'
    - name: Install yarn
      run: corepack enable
    - name: Yarn install everything else
      working-directory: ./staking
      run: yarn install
    - name: Yarn install everything api
      working-directory: ./staking-ts
      run: yarn install
    - name: Install Solana 
      run: |
        sh -c "$(curl -sSfL https://release.solana.com/v1.9.1/install)"
        echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
    - name: Install Anchor
      working-directory: ./staking
      run: npm i -g @project-serum/anchor-cli
    - name: Compile wasms
      working-directory: ./staking
      run: yarn build_wasm
    - name: Start validator
      working-directory: ./staking
      run: yarn test_api

