name: Deploy program 

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.13"
      - name: Install yarn
        run: corepack enable
      - name: Yarn install everything else
        working-directory: ./staking
        run: yarn install
      - name: Install Solana
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.9.1/install)"
          echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      - name: Install Anchor
        working-directory: ./staking
        run: npm i -g @project-serum/anchor-cli
      - name: Generate a keypair for the program
        working-directory: ./staking
        run: solana-keygen new -o ./tests/program.json --no-bip39-passphrase --force
      - name: Generate a keypair for the deployer
        working-directory: ./staking
        run: solana-keygen new -o ./tests/default_wallet.json --no-bip39-passphrase --force
      - name: Connect to the test network
        working-directory: ./staking
        run: solana config set --url http://13.40.33.111:8899 --keypair ./tests/default_wallet.json
      - name: Setup program pubkey as environment variable
        working-directory: ./staking
        run: echo "PROGRAM_KEY=$(solana-keygen pubkey ./tests/program.json" >> $GITHUB_ENV
      - name: Update program address declaration
        working-directory: ./staking
        run: |
          sed -i 's/Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS/${{ env.PROGRAM_KEY }}' programs/staking/src/lib.rs
          sed -i 's/Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS/${{ env.PROGRAM_KEY }}' ./Anchor.toml
          sed -i 's,localnet,http://13.40.33.111:8899' ./Anchor.toml
      - name: Anchor build
        working-directory: ./staking
        run: anchor build
      - name : Anchor deploy
        working-directory: ./staking
        run: anchor build
      - name : Initialize idl
        working-directory: ./staking
        run : anchor init idl ${{ env.PROGRAM_KEY }}

