name: Release

on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Solana Verify CLI
        run: |
          cargo install solana-verify --git https://github.com/Ellipsis-Labs/solana-verifiable-build --rev 098551f
      - name: Build
        working-directory: ./staking
        run: solana-verify build
      - name: Publish program binaries
        uses: svenstaro/upload-release-action@133984371c30d34e38222a64855679a414cb7575
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./staking/target/deploy/*.so
          tag: ${{ github.ref }}
          file_glob: true
