name: Staking Snapshot

on:
  schedule:
    - cron: "0 6 * * 5" # Every Friday at 6:00 UTC
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STAKING_DATA_API_URL: ${{ secrets.STAKING_DATA_API_URL }}
      STAKING_DATA_API_KEY: ${{ secrets.STAKING_DATA_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.75.0

      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/v1.18.16/install)" && \
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Generate Staking Snapshot
        run: |
          export PATH="$HOME/.cargo/bin:$PATH" && \
          solana --version && \
          mkdir -p ~/.config/solana && \
          chmod 755 ~/.config/solana && \
          solana-keygen new --outfile ~/.config/solana/id.json && \
          cd ./staking && \
          cargo build --release && \
          target/release/staking-cli --rpc-url ${{ secrets.STAKING_CLI_RPC_URL }}  save-stake-accounts-snapshot && \
          ls -lah snapshots && \
          node scripts/staking_snapshot.js
