name: Staking Snapshot

on:
  schedule:
    - cron: "0 6 * * 5" # Every Friday at 6:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.19.1"
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.75.0
      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/v1.18.16/install)"
      - name: Generate Staking Snapshot
        working-directory: ./staking
        run: |
          solana-keygen new --outfile ~/.config/solana/id.json && \
          cargo build --release && \
          target/release/staking-cli --rpc-url=${{ secrets.RPC_URL }}  save-stake-accounts-snapshot && \
          ls -lah snapshots && \
          node scripts/staking_snapshot.js
